#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_CPU_S3C6410)		+= elice_hw_board_version.o ../../elice_kernel_info.o elice_battery.o elice_dcc.o

